Repository nextbss/requirekt, pull requests merged in 2020-09, with the labels that each got.

#1 improve documentation
  README.md
  pom.xml
  src/test/kotlin/co/ao/nextbss/requirekt/RequireTest.kt
  target/test-classes/co/ao/nextbss/requirekt/RequireTest.class
Labels: documentation

#3 Converts it to Pure Kotlin
  pom.xml
  src/main/kotlin/ao/co/nextbss/requirekt/ApiException.kt
  src/main/kotlin/ao/co/nextbss/requirekt/ErrorHandler.kt
  src/main/kotlin/ao/co/nextbss/requirekt/ErrorViewModel.kt
  src/main/kotlin/ao/co/nextbss/requirekt/ErrorWrapper.kt
  src/main/kotlin/ao/co/nextbss/requirekt/Preconditions.kt
  src/main/kotlin/co/ao/nextbss/requirekt/ErrorViewModel.java
  src/main/kotlin/co/ao/nextbss/requirekt/ErrorWrapper.java
  src/test/kotlin/ao/co/nextbss/requirekt/RequireTest.kt
  src/test/kotlin/ao/co/nextbss/requirekt/RestApiController.kt
  target/classes/META-INF/requirekt.kotlin_module
  target/classes/co/ao/nextbss/requirekt/ApiException.class
  target/classes/co/ao/nextbss/requirekt/ErrorHandler.class
  target/classes/co/ao/nextbss/requirekt/ErrorViewModel.class
  target/classes/co/ao/nextbss/requirekt/ErrorWrapper.class
  target/classes/co/ao/nextbss/requirekt/PreconditionsKt.class
  target/test-classes/co/ao/nextbss/requirekt/RequireTest.class
  target/test-classes/co/ao/nextbss/requirekt/RestApiController.class
Labels: enhancement

#5 NF - updated workflow
  .github/workflows/blank.yml
Labels: enhancement

#4 NF - Custom error responses
  .gitignore
  pom.xml
  src/main/kotlin/ao/co/nextbss/requirekt/AAACustomErrorViewModel.kt
  src/main/kotlin/ao/co/nextbss/requirekt/AbstractErrorResponse.kt
  src/main/kotlin/ao/co/nextbss/requirekt/ApiException.kt
  src/main/kotlin/ao/co/nextbss/requirekt/CustomErrorBeanFinder.kt
  src/main/kotlin/ao/co/nextbss/requirekt/DefaultErrorViewModel.kt
  src/main/kotlin/ao/co/nextbss/requirekt/ErrorResponse.kt
  src/main/kotlin/ao/co/nextbss/requirekt/ErrorViewModel.kt
  src/main/kotlin/ao/co/nextbss/requirekt/ErrorWrapper.kt
  src/main/kotlin/ao/co/nextbss/requirekt/Preconditions.kt
  src/main/kotlin/ao/co/nextbss/requirekt/SpringContext.kt
  src/main/kotlin/ao/co/nextbss/requirekt/annotation/ErrorResponse.kt
  src/main/kotlin/ao/co/nextbss/requirekt/extensions.kt
  src/main/kotlin/ao/co/nextbss/requirekt/interfaces/Converter.kt
  src/test/kotlin/ao/co/nextbss/requirekt/RequireTest.kt
  src/test/kotlin/ao/co/nextbss/requirekt/RestApiController.kt
  target/classes/META-INF/requirekt.kotlin_module
Labels: enhancement

#7 V1.1.0
  README.md
  pom.xml
  src/main/kotlin/ao/co/nextbss/requirekt/Preconditions.kt
Labels: documentation, enhancement

#8 updated README
  README.md
Labels: documentation
